packages

In [1]:
import numpy as np

tables

In [2]:
table_header = r'''    \sisetup{table-format=2.1}
    \begin{tabular}{c S S S[table-format=1.3] S[table-format=1.3]}
        \toprule
        {Loch} &
        {$a_k \mathbin{/} \unit{\milli\meter}$} &
        {$b_k \mathbin{/} \unit{\milli\meter}$} &
        {$a_k \, / \, a'_k$} &
        {$b_k \, / \, b'_k$} \\
        \midrule
'''
table_footer = r'''        \bottomrule
    \end{tabular}
'''
row_template = r'        {0:.0f} & {1:.1f} & {2:.1f} & {3:.3f} & {4:.3f} \\'

caliper

In [3]:
n0, a0, b0, d0, f0 = np.genfromtxt('data/ausmessung.txt', unpack=True)

print(a0)
print(b0)

[13.5  21.85 30.3  38.7  46.8  54.7  62.7  70.6  15.2 ]
[61.85 54.4  47.   39.5  31.   23.   15.35  7.2  55.8 ]


a-scan

In [4]:
n1, a1, b1 = np.genfromtxt('data/ascan.txt', unpack=True)

da1, db1 = a1/a0, b1/b0

print(n1)
print('\n')
print(a1)
print(b1)
print('\n')
print(da1)
print(db1)
print('\n')

with open('build/tab_1.tex', 'w') as f:
        f.write(table_header)
        for row in zip(n1, a1, b1, da1, db1):
                f.write(row_template.format(*row))
                f.write('\n')
        f.write(table_footer)
with open('build/tab_1.tex', 'r') as f:
    print(f.read())

print('')
print(f'{np.mean(da1)}')
print(f'{np.mean(db1)}')

[ 3.  4.  5.  6.  7.  8.  9. 10. 11.]


[14.7 23.5 32.1 40.8 48.4 56.2 64.2 73.1 17.2]
[63.  55.4 47.8 40.4 32.2 24.4 16.8  8.7 56.8]


[1.08888889 1.07551487 1.05940594 1.05426357 1.03418803 1.0274223
 1.02392344 1.03541076 1.13157895]
[1.01859337 1.01838235 1.01702128 1.02278481 1.03870968 1.06086957
 1.09446254 1.20833333 1.01792115]


    \sisetup{table-format=2.1}
    \begin{tabular}{c S S S[table-format=1.3] S[table-format=1.3]}
        \toprule
        {Loch} &
        {$a_k \mathbin{/} \unit{\milli\meter}$} &
        {$b_k \mathbin{/} \unit{\milli\meter}$} &
        {$a_k \, / \, a'_k$} &
        {$b_k \, / \, b'_k$} \\
        \midrule
        3 & 14.7 & 63.0 & 1.089 & 1.019 \\
        4 & 23.5 & 55.4 & 1.076 & 1.018 \\
        5 & 32.1 & 47.8 & 1.059 & 1.017 \\
        6 & 40.8 & 40.4 & 1.054 & 1.023 \\
        7 & 48.4 & 32.2 & 1.034 & 1.039 \\
        8 & 56.2 & 24.4 & 1.027 & 1.061 \\
        9 & 64.2 & 16.8 & 1.024 & 1.094 \\
        10 & 73.1 & 8.7 & 1.035 & 1.208 \\
   

b-scan

In [5]:
n2, a2, b2 = np.genfromtxt('data/bscan.txt', unpack=True)

da2, db2 = a2/a0, b2/b0

print(n2)
print('\n')
print(a2)
print(b2)
print('\n')
print(da2)
print(db2)
print('\n')

row_inline = r'        {0:.0f} & {{-}} & {1:.1f} & {{-}} & {2:.3f} \\'
with open('build/tab_2.tex', 'w') as f:
        f.write(table_header)
        for row in zip(n2[:7], a2[:7], b2[:7], da2[:7], db2[:7]):
                f.write(row_template.format(*row))
                f.write('\n')
        for row in zip(n2[7:8], b2[7:8], db2[7:8]):
                f.write(row_inline.format(*row))
                f.write('\n')
        for row in zip(n2[8:], a2[8:], b2[8:], da2[8:], db2[8:]):
                f.write(row_template.format(*row))
                f.write('\n')
        f.write(table_footer)
with open('build/tab_2.tex', 'r') as f:
    print(f.read())

print('')
print(f'{np.mean(np.delete(da2, 7))}')
print(f'{np.mean(db2)}')

[ 3.  4.  5.  6.  7.  8.  9. 10. 11.]


[15.1 23.6 32.4 40.8 48.9 56.5 64.7 60.  17.2]
[63.3 55.8 48.2 40.8 33.  24.8 16.8  9.  57.4]


[1.11851852 1.08009153 1.06930693 1.05426357 1.04487179 1.03290676
 1.03189793 0.84985836 1.13157895]
[1.02344382 1.02573529 1.02553191 1.03291139 1.06451613 1.07826087
 1.09446254 1.25       1.02867384]


    \sisetup{table-format=2.1}
    \begin{tabular}{c S S S[table-format=1.3] S[table-format=1.3]}
        \toprule
        {Loch} &
        {$a_k \mathbin{/} \unit{\milli\meter}$} &
        {$b_k \mathbin{/} \unit{\milli\meter}$} &
        {$a_k \, / \, a'_k$} &
        {$b_k \, / \, b'_k$} \\
        \midrule
        3 & 15.1 & 63.3 & 1.119 & 1.023 \\
        4 & 23.6 & 55.8 & 1.080 & 1.026 \\
        5 & 32.4 & 48.2 & 1.069 & 1.026 \\
        6 & 40.8 & 40.8 & 1.054 & 1.033 \\
        7 & 48.9 & 33.0 & 1.045 & 1.065 \\
        8 & 56.5 & 24.8 & 1.033 & 1.078 \\
        9 & 64.7 & 16.8 & 1.032 & 1.094 \\
        10 & {-} & 9.0 & {-} & 1.250 \\
     